micronaut:
  application:
    name: chatServer

---
#tag::static-resources[]
micronaut:
  router:
    static-resources: # <1>
      default:
        enabled: true
        mapping: /**
        paths: classpath:public
#end::static-resources[]